### ISSUE TITLE
WT Data Project mislabeled vehicles 

### ISSUE THREAD

**Issue by GewelReal** [ControlNet/wt-data-project.web#1]
Hello! Friend told me about your fantastic tool at https://wt.controlnet.space/ and it's overall fantastic and easy to use.
Issue is quite a few vehicles are mislabeled. I show 2 very obvious examples in the .jpeg file
![mislabeling](https://user-images.githubusercontent.com/98192750/150610392-0a9d49b1-7124-4736-9ad2-5a8901d2ab1b.jpg)
.

**Comment by ControlNet** [comment]
Hi,

Thank you for your pointing out this. 

The matching of Thunderskill data and WT wiki data is based on name similarity, so it's hard to avoid it. For such wrong matching, I can specify the correct target manually. So, can you list the wrong matching vehicles as many as possible? And I can fix them all.

**Comment by FlareFlo** [comment]
I have been working on a custom tool for parsing WT localization recently, I may be able to offer some sort of API/entry points for anything in-game localization. @ControlNet

**Comment by ControlNet** [comment]
> I have been working on a custom tool for parsing WT localization recently, I may be able to offer some sort of API/entry points for anything in-game localization. @ControlNet

@FlareFlo Sounds interesting. If it contains the mapping between Thunderskill name and Wiki name, it will help a lot.

**Comment by FlareFlo** [comment]
> > I have been working on a custom tool for parsing WT localization recently, I may be able to offer some sort of API/entry points for anything in-game localization. @ControlNet
> 
> @FlareFlo Sounds interesting. If it contains the mapping between Thunderskill name and Wiki name, it will help a lot.

Im not sure where Thunderskill gets their names from, but i can translate the ingame ID to the ingame language. (AFAIK thunderskill uses the same database/csv as the wiki/game do).

**Comment by ControlNet** [comment]
> Im not sure where Thunderskill gets their names from, but i can translate the ingame ID to the ingame language. (AFAIK thunderskill uses the same database/csv as the wiki/game do).

I hope the mapping is like this.  @FlareFlo 
![image](https://user-images.githubusercontent.com/12800094/151459964-35520da4-9e68-40ad-b118-87b888337563.png)

**Comment by FlareFlo** [comment]
> > Im not sure where Thunderskill gets their names from, but i can translate the ingame ID to the ingame language. (AFAIK thunderskill uses the same database/csv as the wiki/game do).
> 
> I hope the mapping is like this.  @FlareFlo 
> ![image](https://user-images.githubusercontent.com/12800094/151459964-35520da4-9e68-40ad-b118-87b888337563.png)
> 

It is exactly like that.
[Units file that i can parse to a json](https://github.com/FlareFlo/wt_csv/blob/master/lang/units.csv)

**Comment by ControlNet** [comment]
> > > Im not sure where Thunderskill gets their names from, but i can translate the ingame ID to the ingame language. (AFAIK thunderskill uses the same database/csv as the wiki/game do).
> > 
> > 
> > I hope the mapping is like this.  @FlareFlo
> > ![image](https://user-images.githubusercontent.com/12800094/151459964-35520da4-9e68-40ad-b118-87b888337563.png)
> 
> It is exactly like that. [Units file that i can parse to a json](https://github.com/FlareFlo/wt_csv/blob/master/lang/units.csv)

Looks great. Can I use this CSV file for data processing in this project? I think it's very helpful.

**Comment by FlareFlo** [comment]
> > > > Im not sure where Thunderskill gets their names from, but i can translate the ingame ID to the ingame language. (AFAIK thunderskill uses the same database/csv as the wiki/game do).
> > > 
> > > 
> > > I hope the mapping is like this.  @FlareFlo
> > > ![image](https://user-images.githubusercontent.com/12800094/151459964-35520da4-9e68-40ad-b118-87b888337563.png)
> > 
> > It is exactly like that. [Units file that i can parse to a json](https://github.com/FlareFlo/wt_csv/blob/master/lang/units.csv)
> 
> Looks great. Can I use this CSV file for data processing in this project? I think it's very helpful. 

Yes, sure. I can offer to export the file to json for a more easier to use interface.

**Comment by ControlNet** [comment]
> > > > Im not sure where Thunderskill gets their names from, but i can translate the ingame ID to the ingame language. (AFAIK thunderskill uses the same database/csv as the wiki/game do).
> > > 
> > > 
> > > I hope the mapping is like this.  @FlareFlo
> > > ![image](https://user-images.githubusercontent.com/12800094/151459964-35520da4-9e68-40ad-b118-87b888337563.png)
> > 
> > 
> > It is exactly like that. [Units file that i can parse to a json](https://github.com/FlareFlo/wt_csv/blob/master/lang/units.csv)
> 
> Looks great. Can I use this CSV file for data processing in this project? I think it's very helpful.

Thanks for your kind. I am using Pandas for processing, so it's fine to be CSV.

**Comment by FlareFlo** [comment]
> > Yes, sure. I can offer to export the file to json for a more easier to use interface.
> 
> @FlareFlo. Thanks for your kind. I am using Pandas for processing, so it's fine to be CSV.

Two notes:

1. The WT CSV files are non-standard and therefore require some extra care
2. Please refer to [here](https://github.com/Warthunder-Open-Source-Foundation/wt_datamine_extractor/blob/master/lang/units.csv) as it is more frequently updated (the other repo is not automatically patched)

**Comment by ControlNet** [comment]
> > > Yes, sure. I can offer to export the file to json for a more easier to use interface.
> > 
> > 
> > @FlareFlo. Thanks for your kind. I am using Pandas for processing, so it's fine to be CSV.
> 
> Two notes:
> 
> 1. The WT CSV files are non-standard and therefore require some extra care
> 2. Please refer to [here](https://github.com/Warthunder-Open-Source-Foundation/wt_datamine_extractor/blob/master/lang/units.csv) as it is more frequently updated (the other repo is not automatically patched)

@FlareFlo Thanks. I'll use that link. Here is one question about the ID suffix. What is the "xxx_0", "xxx_1", "xxx_shop" for?

**Comment by FlareFlo** [comment]
> @FlareFlo Thanks. I'll use that link. Here is one question about the ID suffix. What is the "xxx_0", "xxx_1", "xxx_shop" for?

The `_0` `_1` etc. prefixes are for view-distances, decreasing in length and accuracy the higher the `_x` prefix increases.
 `_shop` is what the hangar would display.
 
 An example of how all the prefixes operate:
![image](https://user-images.githubusercontent.com/78537307/151569433-06480b72-f5f0-4e38-8799-be686abe42d6.png)

**Comment by ControlNet** [comment]
> > @FlareFlo Thanks. I'll use that link. Here is one question about the ID suffix. What is the "xxx_0", "xxx_1", "xxx_shop" for?
> 
> The `_0` `_1` etc. prefixes are for view-distances, decreasing in length and accuracy the higher the `_x` prefix increases. `_shop` is what the hangar would display.
> 
> An example of how all the prefixes operate: ![image](https://user-images.githubusercontent.com/78537307/151569433-06480b72-f5f0-4e38-8799-be686abe42d6.png)

Got it! Thanks.

**Comment by ControlNet** [comment]
The new matching mechanism is applied. The issue is fixed.

**Comment by GewelReal** [comment]
Wow I completely forgot about this!
I'm happy FlareFlo came in with a sophisticated idea
