### ISSUE TITLE
Excel Import

### ISSUE THREAD

**Issue by ChaoticRambo** [ControlNet/wt-data-project.web#12]
You used to be able to easily copy and paste the data into excel and it would correctly paste the data into rows and columns. With the new table presentation for the data, it now just copies each data point into the first column. It would be nice if there was some way to export the table to excel for manual manipulation.

**Comment by ControlNet** [comment]
I just tried. Excel can open csv files, and everything looks fine.

![image](https://user-images.githubusercontent.com/12800094/210153113-1cd2b718-813b-4a71-85a6-6f42c0e38e60.png)

**Comment by ChaoticRambo** [comment]
I guess I was just used to going to the heatmap, selecting the BRs and Countries I was interested in and copying the data directly out of the web page and into excel. Made it easy for me to figure out what vehicles and such made good combos. I can see that I can just pull the master list from this file though.

**Comment by ControlNet** [comment]
Yeah, it's just simple filtering. But I will also consider your idea that allows user directly click to download the table in the web.

**Comment by ControlNet** [comment]
Implemented.
![image](https://user-images.githubusercontent.com/12800094/215467515-1f8ee382-8445-45b3-b922-381841e8eca9.png)
