### ISSUE TITLE
New BR needs to be updated

### ISSUE THREAD

**Issue by JoejoeWang** [ControlNet/wt-data-project.web#15]
When I am searching the win rate of leo2a4, the table shows that its BR is 10.0 instead of 10.3 (the correct one in the game). So does CV90105. I think it's a issue with the new posted BR

**Comment by ControlNet** [comment]
The BR data is collected from the warthunder wiki, so you can check the page for l2a4 here ([https://wiki.warthunder.com/Leopard_2A4](https://wiki.warthunder.com/Leopard_2A4)). Currently, the wiki is not updated for the latest BR. This issue will be solved when the wiki is updated.
