### ISSUE TITLE
Style issue when using Firefox

### ISSUE THREAD

**Issue by markusonnela** [ControlNet/wt-data-project.web#16]
The Dates on the "Win Rate / Date" graph overlap when using Firefox.
![image](https://github.com/ControlNet/wt-data-project.web/assets/67270295/0db12334-7add-4a83-9379-367fe364ec69)

**Comment by ControlNet** [comment]
Now it uses `YY/MM` instead of `YYYY/MM` to make it more readable. Change is applied in 25fc89e8d0eb182d3dd3fc2cdb9abb4b7190aafe.
