### ISSUE TITLE
Fifth line-up Sweden data

### ISSUE THREAD

**Issue by nguykiet44** [ControlNet/wt-data-project.web#17]
Hi, can you check and add data for Sweden's fifth lineup? It is missing.
![Screenshot (109)](https://github.com/ControlNet/wt-data-project.web/assets/97038334/e3d01404-3042-44f2-bc54-1961272930df)
![image](https://github.com/ControlNet/wt-data-project.web/assets/97038334/f8ba36aa-dfed-4038-9d2a-f8937efc0fc5)

**Comment by ControlNet** [comment]
Thanks for reporting that. I'm working on it.

**Comment by ControlNet** [comment]
Fixed in ControlNet/wt-data-project.data@307daac822d25bcef2c3c4c6dd2efb3c1c92cc05
