### ISSUE TITLE
Sweden 5.0 AB

### ISSUE THREAD

**Issue by Scythwolf** [ControlNet/wt-data-project.web#2]
There are no entries in 5.0 Sweden AB despite sweden having the 5.0 J21A1/2/3 lineup there. 

Selection: AB, Aviation, BR-Range 0 
My intuition is that at 5.0 there should be shown all the battles done by the sweden 5.0 lineup. The fielst is empy though

![image](https://user-images.githubusercontent.com/14348376/152866531-aba58dbb-e22b-4270-aa16-f3659823af66.png)

**Comment by ControlNet** [comment]
![image](https://user-images.githubusercontent.com/12800094/152881702-7fceae66-6025-4119-9663-872c3775f837.png)


@Scythwolf Hi, obviously the Sweden 5.0 is not blank. Please check it again.

**Comment by Scythwolf** [comment]
Yes, my bad. Sorry.
