### ISSUE TITLE
Color gradient not showing for main table.

### ISSUE THREAD

**Issue by RealmX1** [ControlNet/wt-data-project.web#20]
![image](https://github.com/ControlNet/wt-data-project.web/assets/30303853/c87b02e2-9f12-473a-9d02-97b3b3a755d9)

It does show for each vehicle though:
![image](https://github.com/ControlNet/wt-data-project.web/assets/30303853/039c8fbd-63c8-4a85-9038-3db0293d5ef3)

**Comment by ControlNet** [comment]
Thanks for letting me know. I'm working on it.

**Comment by RealmX1** [comment]
> Thanks for letting me know. I'm working on it.
Thanks for fixing it so quickly
