### ISSUE TITLE
question regarding CL-13 and suggestions

### ISSUE THREAD

**Issue by notsheram** [ControlNet/wt-data-project.web#23]
Hi, I was just wondering if CL-13 is in the table and if yes, where I can find it?
Also I wanted to suggest maybe including a helicopter table.
That being said: I love your project and would love to donate some money. Maybe an unintrusive banner ad and an ad-free mode which you can earn with a one-time donation over a certain amount. Just some ideas for ya.
Best regards

**Comment by ControlNet** [comment]
> Hi, I was just wondering if CL-13 is in the table and if yes, where I can find it?

I see it's wrongly matched to the Italy CL-13 after 2022-12-19. It's easy to fix. Thank you letting me know.

> Maybe an unintrusive banner ad and an ad-free mode which you can earn with a one-time donation over a certain amount. 

Really appreciate your support. BTW, I don't like ads as it looks really bad to the data visualization UI. A small donation botton in the navbar might be good. You may see it in the near future.

**Comment by ControlNet** [comment]
Fixed in https://github.com/ControlNet/wt-data-project.data/commit/c466354ecf9acc2dfaaeb9b4c5c1cc77a028bbc0
