### ISSUE TITLE
Incorrect data

### ISSUE THREAD

**Issue by Spannerjr** [ControlNet/wt-data-project.web#24]
The winrates for the USA in ground RB and the winrates for Britain in ground RB are different as the US xm1069 ADATS is under the British for winrate calculation
![Screenshot_20240306_011214_Chrome](https://github.com/ControlNet/wt-data-project.web/assets/162392225/87181121-4a8c-4f86-a7f9-fd9270d26685)

**Comment by ControlNet** [comment]
Looks only the latest date (2024-03-06) is affected, I will solve it.

**Comment by ControlNet** [comment]
Fixed in https://github.com/ControlNet/wt-data-project.data/commit/55f6a45fa3d4fb3257c841c0393f24ea92d9635e
