### ISSUE TITLE
Some vehicles under the incorrect tech tree. Also nations updates in ThunderSkill.

### ISSUE THREAD

**Issue by MozzaBurger** [ControlNet/wt-data-project.web#26]
Hello,

There are a few vehicles being put under the wrong tech tree. For instance the 10.3 "it_leopard_2A4" which is the Hungarian 2A4 that's in the Italian tech tree but gets parsed under the German tech tree. It is not the only offender. There's the 6.3 "uk_m109a1" that's along the actual "us_m109a1" in the USA tree and possibly a few others that I can't find on the top of my head.

Also I take the opportunity to point out that ThunderSkill is under new ownership and the guy working on it has implemented a few fixes. Most notably he added the missing newer nations and is working on fixing the missing ranks and such. Just saying in case it may help with the project's future :)

Best regards,
![Screenshot 2024-07-10 184509](https://github.com/ControlNet/wt-data-project.web/assets/175242988/00f2a3ec-22fc-47dc-b916-a6096696f274)

**Comment by ControlNet** [comment]
Thank you for your feedback. These 2 wrongly matched vehicles are fixed in https://github.com/ControlNet/wt-data-project.data/commit/3048f3db6136e8a135d8223dc5c1fe41b668d814.
