### ISSUE TITLE
大佬你好 我下载这个代码之后显示是空白的，请问这个是怎么回事呢？

### ISSUE THREAD

**Issue by neonskk** [ControlNet/wt-data-project.web#4]
![image](https://user-images.githubusercontent.com/77058552/190602752-7d88f4d9-4fe2-4188-a970-3fe98bb2c83e.png)
![image](https://user-images.githubusercontent.com/77058552/190602832-f77d77e2-91cc-4f14-9dc9-c93c07e4107c.png)
![image](https://user-images.githubusercontent.com/77058552/190603080-c8a7055d-3d75-448e-8e5d-6160600ebdc9.png)
望大佬解答疑惑

**Comment by ControlNet** [comment]
这个代码是用ts和rust写的，需要先编译打包。

先编译wasm，
```
cd wasm-utils
wasm-pack build
```
然后编译并打包ts，
```
cd ..
npm install
npm run build:production
```
然后再跑就应该没问题了。

另外如果想要直接跑，可以直接clone "web" branch。

**Comment by neonskk** [comment]
非常感谢大佬的答复，我不会ts和rust，希望能直接跑本地代码或者简单的放在服务器上就能访问，然后我试着
git clone -b web https://github.com/ControlNet/wt-data-project.web.git 这个 "web" branch，但还是在点开index.html后一片空白，请问这个可以解决吗？
![image](https://user-images.githubusercontent.com/77058552/190842149-cc0f784b-e4fd-44e7-a6c0-71e29f525c7d.png)
